### ISSUE TITLE
大佬厉害能不能自定义打卡地址

### ISSUE THREAD

**Issue by gucooing** [ZhibiChan/ncgxy-AutoSignIn#1]
能不能自定义打卡地址

**Comment by Aqwshshdjjd** [comment]
搞个requests，请求，

**Comment by guduzhe-3721** [comment]
大佬，能不能出个详细点教程啊。苦南工打卡久矣

**Comment by Aqwshshdjjd** [comment]
> 大佬，能不能出个详细点教程啊。苦南工打卡久矣

学Python吧

**Comment by gucooing** [comment]
> 

我的分支更新了，到手即用

**Comment by gucooing** [comment]
> > 大佬，能不能出个详细点教程啊。苦南工打卡久矣
> 
> 学Python吧
我的分支更新了，就是没再写多人打卡通知，单人直接用，多人改读取就可以了

**Comment by gucooing** [comment]
> > 大佬，能不能出个详细点教程啊。苦南工打卡久矣
> 
> 学Python吧

而且这玩意是脚本，模拟鼠标键盘在浏览器输入，如果要自定义大部分东西得抓token，请求也得带cookie

**Comment by guduzhe-3721** [comment]
> > > 大佬，能不能出个详细点教程啊。苦南工打卡久矣
> > 
> > 
> > 学Python吧
> 
> 而且这玩意是脚本，模拟鼠标键盘在浏览器输入，如果要自定义大部分东西得抓token，请求也得带cookie



> > 
> 
> 我的分支更新了，到手即用
我这显示连到系统上的设备没有发挥作用，这是咋回事啊/(ㄒoㄒ)/~~
